### PR TITLE
feat(ethers): reexports structs and event from typechain

### PR DESCRIPTION
**Pull request by mathewmeconry**
## Description

This PR adds structs and events to the `osx-ethers` package and fixes problems in the deploy script that weren't catched by the gh workflow triggers.

Task ID: [OS-991](https://aragonassociation.atlassian.net/browse/OS-991)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [x] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have updated the `DEPLOYMENT_CHECKLIST` file in the root folder.
- [x] I have updated the `UPDATE_CHECKLIST` file in the root folder.

[OS-991]: https://aragonassociation.atlassian.net/browse/OS-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Michael-A-Heuer** [comment]
Test should be passing now: https://github.com/aragon/osx/actions/runs/7783995724/job/21224187688

**Comment by Michael-A-Heuer** [comment]
We should first merge https://github.com/aragon/osx/pull/529/files and then merge develop back in here.

**Review by jordaniza — APPROVED** [review]
No further comments, this looks perfectly sensible as a set of type exports.

**Comment by Michael-A-Heuer** [comment]
I had to add the `@ensdomains/ens-contracts` so that we can obtain the resolvers and registries properly, e.g., to use them in osx-plugin-template-hardhat.

**Review by Rekard0 — APPROVED** [review]
LGTM!

**Comment by Michael-A-Heuer** [comment]
> LGTM!, Please make sure appropriate label are assigned and follow up with the publication

We don't have such workflows on this repo. We must manually release according to our checklist,

**Review by jordaniza — APPROVED** [review]
lgtm

**Pull request merged**
